language: rust
matrix:
  include:
    - rust: 1.0.0
      env:
        - LABEL="msrv"
      script:
        - cargo generate-lockfile
        - cargo test --verbose
    - rust: stable
      env:
        - LABEL="no_std"
      script:
        - rustup target add thumbv6m-none-eabi
        - cargo build --target=thumbv6m-none-eabi --verbose
        - cargo test --target=thumbv6m-none-eabi --verbose
    - rust: stable
    - rust: nightly
    - rust: beta
  allow_failures:
    - rust: nightly
sudo: false
