language: rust
matrix:
  include:
    - rust: 1.0.0
      env:
        - LABEL="msrv"
      script:
        - cargo generate-lockfile
        - cargo test --verbose
    - rust: 1.6.0
      env:
        - LABEL="msrv_no_std"
      script:
        - cargo generate-lockfile
        - rustup target add thumbv6m-none-eabi
        - cargo build --target thumbv6m-none-eabi --verbose
    - rust: stable
      env:
        - LABEL="no_std"
      script:
        - rustup target add thumbv6m-none-eabi
        - cargo build --target thumbv6m-none-eabi --verbose
    - rust: stable
    - rust: nightly
    - rust: beta
  allow_failures:
    - rust: nightly
sudo: false

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in target/debug/substring-*; do [ -x "${file}" ] || continue; mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
